version: "3.9"

services:
# Pipelines
  etl_pipeline:
    build:
      context: ./etl_pipeline
      dockerfile: ./Dockerfile
    container_name: etl_pipeline
    image: etl_pipeline:latest
    volumes:
      - ./etl_pipeline:/opt/dagster/app
    env_file:
      - .env
    ports:
      - "4000:4000" 
    networks:
      - de_network

  # PostgreSQL
  quakeflow_japan_psql:
    image: postgres:15
    container_name: quakeflow_japan_psql
    volumes:
      - ./postgresql:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    env_file:
      - .env
    networks:
      - de_network

  # MinIO
  quakeflow_japan_minio:
    image: minio/minio
    container_name: quakeflow_japan_minio
    hostname: quakeflow_japan_minio
    ports:
      - "9000:9000"
      - "9001:9001"
    command: [ "server", "/data", "--console-address", ":9001" ]
    volumes:
      - ./minio:/data
    env_file:
      - .env
    networks:
      - de_network

  # MinIO Client
  quakeflow_japan_mc:
    image: minio/mc
    container_name: quakeflow_japan_mc
    hostname: quakeflow_japan_mc
    restart: on-failure
    env_file:
      - .env
    entrypoint: >
      /bin/sh -c "
        until (/usr/bin/mc config host add quakeflow_japan_minio http://quakeflow_japan_minio:9000 $MINIO_ROOT_USER $MINIO_ROOT_PASSWORD); do
          echo '...waiting for minio...' && sleep 1;
        done;
        /usr/bin/mc mb quakeflow_japan_minio/warehouse;
        /usr/bin/mc policy set public quakeflow_japan_minio/warehouse;
        exit 0;"
    depends_on:
      - quakeflow_japan_minio
    networks:
      - de_network

  # Dagster build (custom)
  quakeflow_japan_dagster:
    container_name: quakeflow_japan_dagster
    build:
      context: ./dagster
    restart: on-failure
    expose:
      - "4001"
    networks:
      - de_network


  # Dagster UI (Dagit)
  quakeflow_japan_dagit:
    image: quakeflow_japan_dagster:latest
    entrypoint:
      - dagit
      - -h
      - "0.0.0.0"
      - -p
      - "3001"
      - -w
      - workspace.yaml
    container_name: quakeflow_japan_dagit
    expose:
      - "3001"
    ports:
      - "3001:3001"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./dagster_home:/opt/dagster/dagster_home
    env_file:
      - .env
    networks:
      - de_network

  # Dagster Daemon
  quakeflow_japan_daemon:
    image: quakeflow_japan_dagster:latest
    entrypoint:
      - dagster-daemon
      - run
    container_name: quakeflow_japan_daemon
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./dagster_home:/opt/dagster/dagster_home
    env_file:
      - .env
    networks:
      - de_network

  # PySpark + Jupyter
  quakeflow_japan_pyspark:
    image: jupyter/pyspark-notebook:latest
    container_name: quakeflow_japan_pyspark
    ports:
      - "8888:8888"
    volumes:
      - ./notebooks:/home/jovyan/work
    environment:
      - JUPYTER_ENABLE_LAB=yes
    networks:
      - de_network

networks:
  de_network:
    driver: bridge
    name: de_network
