analytics:
  outputs:
    dev:
      dbname: seismodistr_warehouse
      host: localhost
      pass: warehouse_pass
      port: 5432
      schema: analytics
      threads: 1
      type: postgres
      user: warehouse_user
  target: dev
